### ISSUE TITLE
Sofia-SIP from unimrcp-deps-1.5.0 fails to build on debian 9.1 with openssl 1.1.0f (25 May 2017)

### ISSUE THREAD

**Issue by tjanu** [unispeech/unimrcp#204]
Hi,

I didn't see this issue mentioned anywhere else, but here on my debian 9.1 box with openssl 1.1.0f installed, The build of unimrcp-deps 1.5.0 fails with this error message:

tport_tls.c: In function ‘tls_post_connection_check’:                                                                                                                   
tport_tls.c:596:33: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’                                                                               
   tls_parse_extensions(tls, cert->cert_info->extensions);                                                                                                                    
                                 ^~                                                                                  
Makefile:1080: recipe for target 'tport_tls.lo' failed                                                               

After some digging, it seems that yes, X509 aka struct x509_st is not defined anywhere in the headers provided with the debian package of openssl 1.1.0f

Testing the same on debian 8.9 with openssl 1.0.1t works flawlessly.

**Comment by achaloyan** [comment]
Thanks for not only submitting the problem but also providing a fix.
I personally have not tried to build against newer openssl 1.1.0f, but will apply your change when have got some spare time to verify it.
Another temporary option to consider would be not to use openssl by passing --without-openssl to ./configure.

**Comment by scgm11** [comment]
How can I pass  --without-openssl to  build-dep-libs.sh?

ubuntu 18.04 no longer compile due to this issue.

**Comment by achaloyan** [comment]
Not to build-dep-libs.sh itself, but to ./configure of Sofia-SIP. See build_sofia() inside the script.

**Comment by DRoet** [comment]
Would be nice to see a patch now that debian 9 is getting more common 👍
